### ISSUE TITLE
Events are applied multiple times when fetching aggregate through snapshot store

### ISSUE THREAD

**Issue by gquemener** [prooph/snapshotter#30]
I have recreated an environment to reproduce this issue.
You will find it here: https://github.com/gquemener/prooph-snapshotter-issue-poc.

Basically, the snapshotter applies the events multiple times on aggregate root.

I haven't yet detected the root cause of this issue, but I'm suspecting something around the `persistBlockSize` of the `PdoEventStoreProjector` as the issue seems to appear only when the event stream contain more than 1000 events (1000 being the default `persistBlockSize`).

**Comment by enumag** [comment]
Not sure but it might have something to do with the bad error handling in PostgresEventStore.

**Comment by prolic** [comment]
@gquemener can you try with latest pdo-event-store master branch?

**Comment by gquemener** [comment]
It doesn't look like it changes something @prolic 

```bash
➜ php git:(master) ✗ composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing prooph/pdo-event-store (v1.5.2)
  - Installing prooph/pdo-event-store (dev-master 5d53d7a): Loading from cache
Writing lock file
Generating autoload files
➜ php git:(master) ✗ docker-compose exec pgsql psql --user dev dev                                                                                                                                                                                    [0]
psql (9.4.15)
Type "help" for help.

dev=# truncate snapshots ;
TRUNCATE TABLE
dev=# truncate projections ;
TRUNCATE TABLE
dev=# \q
➜ php git:(master) ✗ docker-compose run --rm php php bin/demo.php
Repository without snapshot store
1006 events were applied 1 times.

Repository with snapshot store
1000 events were applied 2 times.
6 events were applied 3 times.
```

(update here: https://github.com/gquemener/prooph-snapshotter-issue-poc/tree/update-pdo-event-store)

**Comment by gquemener** [comment]
As I suspected there is something wrong going on around the `persistBlockSize`.

Setting it to `100` generates the following result:

```bash
➜ snapshotter-issue git:(update-pdo-event-store) ✗ dc run --rm php php bin/demo.php
Repository without snapshot store
1006 events were applied 1 times.

Repository with snapshot store
100 events were applied 2 times.
100 events were applied 3 times.
100 events were applied 4 times.
100 events were applied 5 times.
100 events were applied 6 times.
100 events were applied 7 times.
100 events were applied 8 times.
100 events were applied 9 times.
100 events were applied 10 times.
100 events were applied 11 times.
6 events were applied 12 times.
```

Still investigating...

**Comment by gquemener** [comment]
When the `SnapshotReadModel::stack` method is called, it will try to load the aggregate root from the repository (https://github.com/prooph/snapshotter/blob/master/src/SnapshotReadModel.php?utf8=%E2%9C%93#L78).

At this point, the snapshot does not exist yet, so it will replay all the events from the event store on the aggregate root (https://github.com/prooph/event-sourcing/blob/v5.2.0/src/Aggregate/AggregateRepository.php#L227).

But then, these events will again be replayed in the initial `SnapshotReadModel::stack` method (https://github.com/prooph/snapshotter/blob/master/src/SnapshotReadModel.php?utf8=%E2%9C%93#L88).

I fail to see the bigger picture here, but that doesn't sound right.

**Comment by gquemener** [comment]
Something has just struke me.

What if the aggregate root itself prevented an old event to be replayed another time?
I mean, there's no sense to apply an event which version is `10` when the aggregate root current version is `85`, is it?

I suggest to change the `EventSourcedTrait::replay` implementation by

```php
    protected function replay(Iterator $historyEvents): void
    {
        foreach ($historyEvents as $pastEvent) {
            if ($this->version >= $pastEvent->version()) {
                continue;
            }

            /** @var AggregateChanged $pastEvent */
            $this->version = $pastEvent->version();

            $this->apply($pastEvent);
        }
    }
```

What d'you think @prolic?
I'm tempted to create a PR to see how the test suite reacts!

EDIT: This change does fix the issue shown in the repository I've created.

```bash
➜ snapshotter-issue git:(update-pdo-event-store) ✗ dc run --rm php php bin/demo.php
Repository without snapshot store
1006 events were applied 1 times.

Repository with snapshot store
1006 events were applied 1 times.
```

**Comment by codeliner** [comment]
very good showcase @gquemener . One of the best bug reports I ever saw :+1: 

What did I do to narrow down the problem?

I modified your demo.php to use a block size of 100 and after first persist call (after 100 events) I stopped the script and took a look at the snapshot of the aggregate.

I see that the `eventsCount` property of your example aggregate already contains all 1006 events.
The first 100 events have a count of 2 and the rest have a count of 1.

So you're right with your first observation and it is definitely a bug. 
The SnapshotReadModel should not apply any events itself but only use the current aggregate derived from the repository.

Your other observation is also explainable:
```
Repository with snapshot store
100 events were applied 2 times.
100 events were applied 3 times.
100 events were applied 4 times.
100 events were applied 5 times.
100 events were applied 6 times.
100 events were applied 7 times.
100 events were applied 8 times.
100 events were applied 9 times.
100 events were applied 10 times.
100 events were applied 11 times.
6 events were applied 12 times.
```

After each persist SnapshotReadModel clears the internal cache: https://github.com/prooph/snapshotter/blob/master/src/SnapshotReadModel.php?utf8=%E2%9C%93#L107

So in the first round AR snapshot contains 100 events handled twice and 906 events handled once.

Next round:
snapshot projection is at stream position 100.
AR is loaded with repository from snapshot. 
Repository applies 906 events again, because snapshot says I only saw 100 events so far. Which is not true as we know from round 1.
Current state:
1006 Events applied 2 times

Now the SnapshotReadModel takes the next 100 events and also applies them again:
AR state on next persist call:
100 Events applied 2 times <-- first 100 events are not applied again neither by repository nor snapshot read model
100 Events applied 3 times <- the 100 events handled within current persist round, first reapplied by repository and then a second time by SnapshotReadModel + earlier apply from round one
806 Events applied 2 times <- Rest of the events

and so on.

I think we should remove the apply call: https://github.com/prooph/snapshotter/blob/master/src/SnapshotReadModel.php?utf8=%E2%9C%93#L88

But I need to think about it tomorrow again. TBH I don't know why the SnapshotReadModel behaves this way. Maybe simply a mistake introduced by too much complexity. Not sure.

**Comment by gquemener** [comment]
If you remove the apply call, then the newly stacked events (after `aggregateCache` has been populated with the aggregate) will not be applied (thus the snapshot will be incorrect in the end).

I think 🤔 ...

**Comment by codeliner** [comment]
If we look at the old snapshot mechanism of event-store v6 we can identify significant differences.
v6:
event version (= AR version) % snapshotInterval === 0 -> then take a snapshot

This is the expected behavior of a snapshotting mechanism but current implementation works completely different and we should change that.

Instead of applying events the SnapshotReadModel should only do the following

SnapshotReadModel::stack
event.metadata._version (= AR version) % snapshotInterval === 0 -> then
schedule TakeSnapshot on next persist

SnapshotReadModel::persist
takeSnapshot of every scheduled AR by loading it from repository, taking the snapshot and then clear identityMap of repository

I try to provide a PR later the day, except someone would like to take over and is faster than me.
